- name: copy file
  hosts: deploys
  gather_facts: yes
  become: yes
  become_user: administrator

  tasks:
    - name: copy file auditsettings.ps1
      ansible.windows.win_copy:
       src: ~/.ssh/ansible_karlson/auditsettings.ps1
       dest: c:\temp\
      register: script_return
    - debug:
        msg: "{{ script_return }}"

    - name: copy file NNIT_Windows_Server_Audit
      ansible.windows.win_copy:
       src: ~/.ssh/ansible_karlson/NNIT_Windows_Server_Audit.ps1
       dest: c:\temp\
      register: script_return
    - debug:
        msg: "{{ script_return }}"

    - name: deploy auditsettings
      ansible.windows.win_powershell:
        path: C:\temp\auditsettings.ps1
        remote_src: true

    - name: Import create auditreport
      import_playbook: createauditreport.yml
